[package]
name = "mercatoria_rust"
version = "0.1.0"
authors = ["Jessica Taylor <jessi.liu.taylor@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.32"
sha2 = "0.9.2"
